<?php

/**
 * Created by PhpStorm.
 * User: Carlos Parada Schulthess
 * Date: 03-08-17
 * Time: 09:45
 */


use PHPUnit\Framework\TestCase;

#require '../src/Calculadora.php';
//require '../src/utils/Calculadora.php';

class CampoTest extends TestCase
{

    private $calc;

    public function setUp()
    {
        //parent::setUp(); // TODO: Change the autogenerated stub
        #$this->calc = new Calculadora();

    }

    public function test_telefono(){

    }



    /*
    public function numeros(){
        return [
            [2,3,5],
            [4,3,7],
            [2,2,4],
            [2,4,6],
            [2,5,7]
        ];
    }

    public function testAssert() {
        $this->assertTrue(true, 'Debe ser Verdadero');
    }

    /**
     * @dataProvider numeros
     *
     * @param $x
     * @param $y
     * @param $result
     */
     /*
    public function test_sumar($x, $y, $result){
        $this->assertEquals($result, $this->calc->sumar($x,$y));
    }

    public function test_resta(){
        $this->assertEquals(1, $this->calc->restar(3,2));
    }
    */

}
